name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  super-lint:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Get your source code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run Super-Linter
      - name: Super-Linter
        uses: super-linter/super-linter@v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
